---
version: "2.1"
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    volumes:
      - ${CONFIGDIR}/tautulli/:/config
      - ${CONFIGDIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    restart: unless-stopped

  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/requestrr/:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 4545:4545
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ${MEDIADIR}/downloads/:/downloads
      - ${CONFIGDIR}/transmission/:/config
      - ${MEDIADIR}/downloads/:/watch
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${MEDIADIR}/downloads/:/downloads
      - ${CONFIGDIR}/transmission/:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 8112:8112
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped

  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/overseerr:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 5055:5055
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: apoorva.club
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - ${CONFIGDIR}/shared:/shared

  muximux:
    image: ghcr.io/linuxserver/muximux
    container_name: muximux
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/muximum/:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 1234:8010
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr_4k
    restart: unless-stopped
    ports:
      - 17878:7878
    volumes:
      - ${CONFIGDIR}/radarr4k/:/config
      - ${MEDIADIR}/Media/Movies4K/:/movies
      - ${MEDIADIR}/downloads/:/downloads
      - ${CONFIGDIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/heimdall/:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 11080:80
      - 11443:443
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FB_BASEURL=/filebrowser
    ports:
      - 7812:8080
    volumes:
      - ${MEDIADIR}:/data
      - ${CONFIGDIR}/droppy/:/config
      - ${CONFIGDIR}/shared:/shared
    restart: always

  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=IST
    volumes:
      - ${CONFIGDIR}/duplicati/:/config
      - ${MEDIADIR}/Backups/:/backups
      - ${CONFIGDIR}:/source
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 8200:8200
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 9999:8080

  guacamole:
    container_name: guacamole
    image: oznu/guacamole
    volumes:
      - ${CONFIGDIR}/guacamole/:/config
      - ${CONFIGDIR}/shared:/shared
    ports:
      - 9600:8080
    environment:
      - EXTENSIONS=auth-totp

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
