version: "2.1"
services:
  vpn:
    container_name: nord_vpn_IN
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN # Required
    environment:
      - USER=${VPN_USERID} # Required
      - PASS=${VPN_PASSWD}
      - CONNECT= in105
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24 # So it can be accessed within the local network
    #    network_mode : bridge
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge_vpn_IN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${MEDIADIR}/downloads/:/downloads
      - ${CONFIGDIR}/deluge/:/config
    network_mode: "service:vpn"
    #    ports:
    #      - 8112:8112
    #      - 6881:6881
    #      - 6881:6881/udp
    restart: unless-stopped
