version: "2.1"
services:
  vpn:
    container_name: nord_vpn_IN
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN # Required
    environment:
      - USER=${VPN_USERID} # Required
      - PASS=${VPN_PASSWD}
      - CONNECT= in105
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24 # So it can be accessed within the local network
    #    network_mode : bridge
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ${CONFIGDIR}/shared:/shared

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent_vpn_IN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${MEDIADIR}/downloads/:/downloads
      - ${CONFIGDIR}/qbittorrent/:/config
      - ${CONFIGDIR}/shared:/shared
    network_mode: "service:vpn"
    restart: unless-stopped
